directories:
  output: release
  buildResources: build
appId: com.Akimov.react-vtb
productName: VTB
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - package.json
extraMetadata:
  main: dist/main.js
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: assets/image.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: VTB
electronVersion: 38.3.0
